import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";
import { parseStudentImportFile } from "./importFile";

describe("student Excel import parsing", () => {
  it("finds the real header row after a workbook title and preserves common roster aliases", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([
      ["Student roster export"],
      [],
      ["First Name", "Surname", "Email ID", "Registration Number", "Department"],
      ["Asha", "Rao", "asha@example.edu", "REG-22", "ECE"],
    ]);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Roster");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    const rows = await parseStudentImportFile(new File([bytes], "roster.xlsx"));
    expect(rows).toEqual([{ "First Name": "Asha", Surname: "Rao", "Email ID": "asha@example.edu", "Registration Number": "REG-22", Department: "ECE" }]);
  });

  it("ignores blank-leading columns and preserves typed numeric identifiers", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([["", "", "Registration No", "Email", "Name", "Semester"], ["", "", 1042, "typed@example.edu", "Typed Student", 3]]);
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Students");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    const rows = await parseStudentImportFile(new File([bytes], "typed.xls"));
    expect(rows[0]).toMatchObject({ "Registration No": "1042", Email: "typed@example.edu", Name: "Typed Student", Semester: "3" });
  });

  it("finds headers after several preamble rows and supports alternate aliases", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([["Export generated by Forms"], ["Do not edit this file"], [], ["Student Full Name", "Mail", "USN", "Course", "Section"], ["Ravi Kumar", "ravi@example.edu", "1XX22", "BCA", "A"]]);
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Form Responses");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    const rows = await parseStudentImportFile(new File([bytes], "forms.xlsx"));
    expect(rows).toEqual([{ "Student Full Name": "Ravi Kumar", Mail: "ravi@example.edu", USN: "1XX22", Course: "BCA", Section: "A" }]);
  });

  it("returns no rows when a worksheet has no recognizable roster header", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([["Report title"], ["Created", "Total"], ["today", 5]]);
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Report");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    await expect(parseStudentImportFile(new File([bytes], "report.xlsx"))).resolves.toEqual([]);
  });
});
