import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";
import { parseStudentImportFile } from "./importFile";

const headers = ["Name", "Email", "Username", "Student ID", "USN", "Branch", "Semester", "Section", "Class"];

describe("student Excel import parsing", () => {
  it("finds the canonical header row after a workbook title and preserves typed values", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([["Student roster export"], [], headers, ["Asha Rao", "asha@example.edu", "asha.rao", "REG-22", "USN-22", "ECE", "3", "A", "BCA"]]);
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Roster");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    await expect(parseStudentImportFile(new File([bytes], "roster.xlsx"))).resolves.toEqual([{ Name: "Asha Rao", Email: "asha@example.edu", Username: "asha.rao", "Student ID": "REG-22", USN: "USN-22", Branch: "ECE", Semester: "3", Section: "A", Class: "BCA" }]);
  });

  it("ignores blank-leading columns while requiring every canonical field", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([["", "", ...headers], ["", "", "Typed Student", "typed@example.edu", "typed.student", 1042, "USN1042", "ECE", 3, "A", "BCA"]]);
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Students");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    const rows = await parseStudentImportFile(new File([bytes], "typed.xls"));
    expect(rows[0]).toMatchObject({ "Student ID": "1042", Email: "typed@example.edu", Name: "Typed Student", Semester: "3", USN: "USN1042" });
  });

  it("finds the canonical header after several preamble rows", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([["Export generated by Forms"], ["Do not edit this file"], [], headers, ["Ravi Kumar", "ravi@example.edu", "ravi.kumar", "REG-1", "1XX22", "BCA", "2", "A", "BCA"]]);
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Form Responses");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    await expect(parseStudentImportFile(new File([bytes], "forms.xlsx"))).resolves.toHaveLength(1);
  });

  it("rejects a workbook with no canonical roster template header", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([["Report title"], ["Created", "Total"], ["today", 5]]);
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Report");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    await expect(parseStudentImportFile(new File([bytes], "report.xlsx"))).rejects.toThrow("Roster template headers are incomplete");
  });

  it("rejects alias-only roster headers so the downloadable template remains the source of truth", async () => {
    const worksheet = XLSX.utils.aoa_to_sheet([["First Name", "Email ID", "Registration Number"], ["Asha", "asha@example.edu", "REG-22"]]);
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Roster");
    const bytes = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
    await expect(parseStudentImportFile(new File([bytes], "legacy.xlsx"))).rejects.toThrow("Roster template headers are incomplete");
  });
});
