import { useState } from "react";
import { ArrowRight, Building2, GraduationCap, Loader2, ShieldCheck, UsersRound } from "lucide-react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PasswordInput } from "@/components/PasswordInput";
import { trpc } from "@/lib/trpc";

const destinations = { ADMIN: "/admin", TEACHER: "/teacher", STUDENT: "/student" } as const;
const roles = [{ value: "ADMIN", label: "Institution Admin", icon: Building2, copy: "School or college operations" }, { value: "TEACHER", label: "Teacher", icon: UsersRound, copy: "Roster and assessment studio" }, { value: "STUDENT", label: "Student", icon: GraduationCap, copy: "Assigned assessment console" }] as const;

export default function Login() {
  const [, navigate] = useLocation(); const utils = trpc.useUtils(); const [role, setRole] = useState<(typeof roles)[number]["value"]>("STUDENT"); const [institutionCode, setInstitutionCode] = useState(""); const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const login = trpc.auth.login.useMutation({ onSuccess: async result => { try { sessionStorage.setItem("lms-credential-session", "1"); sessionStorage.removeItem("manus-cookie"); localStorage.removeItem("manus-runtime-user-info"); } catch {} utils.auth.me.setData(undefined, result.data.user); await utils.auth.me.invalidate(); toast.success("Secure session established."); navigate(destinations[result.data.user.role as keyof typeof destinations]); }, onError: error => toast.error(error.message) });
  return <main className="blueprint-surface flex min-h-screen items-center justify-center p-4 sm:p-8"><section className="blueprint-panel w-full max-w-2xl p-6 sm:p-8"><Link href="/" className="eyebrow text-cyan-200 hover:text-white">← RETURN TO NORTHSTAR</Link><div className="mt-6 flex items-center gap-3"><ShieldCheck className="size-7 text-cyan-300" /><div><p className="eyebrow">PRE-PROVISIONED ACCESS</p><h1 className="mt-1 text-3xl font-semibold text-white">Sign in to your workspace</h1></div></div><p className="mt-3 text-sm leading-6 text-blue-100/70">Select the role assigned to you and enter the institution code and credentials issued by your Administrator or Teacher.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{roles.map(item => { const Icon = item.icon; const selected = role === item.value; return <button key={item.value} type="button" onClick={() => setRole(item.value)} className={`rounded-xl border p-4 text-left transition ${selected ? "border-cyan-300 bg-cyan-300/10" : "border-white/15 bg-slate-950/20 hover:border-white/35"}`}><Icon className="size-5 text-cyan-300" /><p className="mt-3 text-sm font-semibold text-white">{item.label}</p><p className="mt-1 text-xs text-blue-100/60">{item.copy}</p></button>; })}</div><form onSubmit={event => { event.preventDefault(); login.mutate({ role, institutionCode, identifier, password }); }} className="mt-7 grid gap-4"><label className="text-sm font-medium text-blue-50">Institution code<Input required value={institutionCode} onChange={event => setInstitutionCode(event.target.value.toUpperCase())} className="mt-2 border-white/20 bg-slate-950/40 font-mono uppercase text-white" placeholder="E.G., NORTH-7K29X" autoComplete="organization" /></label><label className="text-sm font-medium text-blue-50">{role === "STUDENT" ? "Username, USN, or roll number" : "Email or username"}<Input required value={identifier} onChange={event => setIdentifier(event.target.value)} className="mt-2 border-white/20 bg-slate-950/40 text-white" autoComplete="username" /></label><label className="text-sm font-medium text-blue-50">Password<PasswordInput required value={password} onChange={event => setPassword(event.target.value)} minLength={8} className="mt-2 border-white/20 bg-slate-950/40 text-white" autoComplete="current-password" /></label><Button disabled={login.isPending} className="w-full bg-cyan-300 text-[#05205c] hover:bg-cyan-200">{login.isPending && <Loader2 className="mr-2 size-4 animate-spin" />}Sign in securely<ArrowRight className="ml-2 size-4" /></Button></form><p className="mt-6 text-center text-sm text-blue-100/70">No issued credentials? <Link href="/signup" className="font-semibold text-cyan-200 hover:text-white">View account access guidance</Link>.</p></section></main>;
}
