import { useState } from "react";
import { BookOpenCheck, Download, Loader2, Send, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BlueprintShell } from "@/components/BlueprintShell";
import { StudentImportPanel } from "@/components/StudentImportPanel";
import { ActivityLogPanel } from "@/components/ActivityLogPanel";
import { trpc } from "@/lib/trpc";

const emptyStudent = { name: "", email: "", username: "", temporaryPassword: "", studentId: "" };
const emptyAssessment = { title: "", durationMinutes: "30", accessCode: "", questionText: "", firstOption: "", secondOption: "", thirdOption: "", fourthOption: "", correctOption: "a" };

function makeCsv(rows: Array<Array<string | number | null | undefined>>) {
  return rows.map(row => row.map(value => `"${String(value ?? "").replaceAll('"', '""')}"`).join(",")).join("\n");
}

function downloadCsv(name: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url);
}

export default function TeacherDashboard() {
  const utils = trpc.useUtils();
  const [studentForm, setStudentForm] = useState(emptyStudent);
  const [assessmentForm, setAssessmentForm] = useState(emptyAssessment);
  const [filter, setFilter] = useState("");
  const overview = trpc.people.teacher.overview.useQuery();
  const tests = trpc.assessments.teacherList.useQuery();
  const results = trpc.assessments.teacherResults.useQuery();
  const createStudent = trpc.people.teacher.createStudent.useMutation({ onSuccess: () => { toast.success("Student created inside your teaching scope."); setStudentForm(emptyStudent); void utils.people.teacher.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const createAssessment = trpc.assessments.create.useMutation({ onSuccess: () => { toast.success("Validated MCQ assessment saved as a draft."); setAssessmentForm(emptyAssessment); void utils.assessments.teacherList.invalidate(); }, onError: error => toast.error(error.message) });
  const publish = trpc.assessments.publish.useMutation({ onSuccess: () => { toast.success("Assessment published."); void utils.assessments.teacherList.invalidate(); }, onError: error => toast.error(error.message) });
  const assign = trpc.assessments.assign.useMutation({ onSuccess: result => { toast.success(`${result.data.created} student assignments created; ${result.data.existing} already existed.`); void utils.assessments.teacherList.invalidate(); }, onError: error => toast.error(error.message) });
  const data = overview.data?.data as { metrics?: Record<string, number>; students?: Array<{ id: number; name: string | null; email: string | null; status: string; profile?: { studentId?: string | null; branch?: string | null } }> } | undefined;
  const metrics = data?.metrics ?? {}; const students = data?.students ?? [];
  const normalizedFilter = filter.trim().toLowerCase();
  const visibleStudents = students.filter(student => !normalizedFilter || [student.name, student.email, student.profile?.studentId, student.profile?.branch, student.status].some(value => String(value ?? "").toLowerCase().includes(normalizedFilter)));
  const visibleTests = (tests.data?.data ?? []).filter(test => !normalizedFilter || [test.title, test.status, test.accessCode].some(value => String(value ?? "").toLowerCase().includes(normalizedFilter)));
  const visibleResults = (results.data?.data ?? []).filter(result => !normalizedFilter || [result.assessmentTitle, result.studentName, result.studentEmail, result.status].some(value => String(value ?? "").toLowerCase().includes(normalizedFilter)));
  const activeStudentIds = students.filter(student => student.status === "ACTIVE").map(student => student.id);
  const exportStudents = () => downloadCsv("student-directory.csv", makeCsv([["Name", "Email", "Student ID", "Branch", "Status"], ...students.map(student => [student.name, student.email, student.profile?.studentId, student.profile?.branch, student.status])]));
  const exportResults = () => downloadCsv("assessment-results.csv", makeCsv([["Assessment", "Student", "Email", "Status", "Score", "Percentage", "Integrity events", "Submitted"], ...(results.data?.data ?? []).map(result => [result.assessmentTitle, result.studentName, result.studentEmail, result.status, result.score, result.percentage, result.violationCount, result.submittedAt ? new Date(result.submittedAt).toISOString() : ""])]));
  return <BlueprintShell role="TEACHER"><header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="eyebrow">TEACHER / ASSESSMENT OPERATIONS</p><h1 className="mt-2 text-3xl font-semibold text-white">Assessment studio</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-blue-100/70">Create students and timed MCQ assessments inside your ownership boundary. Every participant, assignment, attempt, score, and integrity event is anchored to server-side relationships.</p></div><label className="block text-xs font-semibold text-blue-100/75">Filter managed records<Input value={filter} onChange={event => setFilter(event.target.value)} className="mt-1.5 w-full border-white/20 bg-slate-950/40 text-white lg:w-64" placeholder="Student, assessment, status…" /></label></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["My students", metrics.students ?? 0], ["Assessments", metrics.assessments ?? 0], ["Assignments", metrics.assignments ?? 0], ["Attempts", metrics.attempts ?? 0]].map(([label, value]) => <div key={String(label)} className="metric-card"><BookOpenCheck className="size-5 text-cyan-300" /><span>{label}</span><strong>{value}</strong></div>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="blueprint-panel p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">STUDENT DIRECTORY</p><h2 className="mt-1 text-xl font-semibold text-white">Manual student provisioning</h2></div><button onClick={exportStudents} className="inline-flex items-center gap-2 text-xs font-bold text-cyan-200 hover:text-white"><Download className="size-4" />Export CSV</button></div><form onSubmit={event => { event.preventDefault(); createStudent.mutate(studentForm); }} className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(studentForm).map(([key, value]) => <label key={key} className="text-xs font-semibold text-blue-100/75">{key.replace(/([A-Z])/g, " $1")}<Input required={key !== "studentId"} value={value} type={key === "temporaryPassword" ? "password" : "text"} onChange={event => setStudentForm(current => ({ ...current, [key]: event.target.value }))} className="mt-1.5 border-white/20 bg-slate-950/40 text-white" /></label>)}<Button disabled={createStudent.isPending} className="w-fit bg-cyan-300 text-[#05205c] hover:bg-cyan-200">{createStudent.isPending && <Loader2 className="mr-2 size-4 animate-spin" />}Create student</Button></form><div className="mt-5 max-h-64 overflow-auto">{visibleStudents.length ? <table className="technical-table"><thead><tr><th>Student</th><th>ID</th><th>Branch</th><th>Status</th></tr></thead><tbody>{visibleStudents.map(student => <tr key={student.id}><td><p className="font-medium text-white">{student.name}</p><p className="text-xs text-blue-100/60">{student.email}</p></td><td>{student.profile?.studentId || "—"}</td><td>{student.profile?.branch || "—"}</td><td><span className="technical-chip">{student.status}</span></td></tr>)}</tbody></table> : <p className="empty-state">No students match the current filter.</p>}</div></div>
      <div className="blueprint-panel p-5"><p className="eyebrow">MCQ BLUEPRINT</p><h2 className="mt-1 text-xl font-semibold text-white">Create a secured draft</h2><form onSubmit={event => { event.preventDefault(); const startAt = new Date(Date.now() + 5 * 60_000); const endAt = new Date(startAt.getTime() + 90 * 60_000); createAssessment.mutate({ title: assessmentForm.title, startAt, endAt, durationMinutes: Number(assessmentForm.durationMinutes), maxAttempts: 1, accessCodeEnabled: Boolean(assessmentForm.accessCode), accessCode: assessmentForm.accessCode || undefined, randomizeQuestions: true, randomizeOptions: true, negativeMarking: false, antiCheat: { requireFullscreen: true, detectTabSwitch: true, detectWindowBlur: true, detectFullscreenExit: true, detectClipboard: true, detectContextMenu: true, detectShortcuts: true, violationThreshold: 5, autoSubmitOnThreshold: true }, questions: [{ questionText: assessmentForm.questionText, options: [{ id: "a", text: assessmentForm.firstOption }, { id: "b", text: assessmentForm.secondOption }, { id: "c", text: assessmentForm.thirdOption }, { id: "d", text: assessmentForm.fourthOption }], correctOptionId: assessmentForm.correctOption, marks: 1, negativeMarks: 0 }] }); }} className="mt-5 grid gap-3">{([["title", "Assessment title"], ["durationMinutes", "Duration (minutes)"], ["accessCode", "Access code (optional)"], ["questionText", "MCQ question"], ["firstOption", "Option A"], ["secondOption", "Option B"], ["thirdOption", "Option C"], ["fourthOption", "Option D"]] as const).map(([key, label]) => <label key={key} className="text-xs font-semibold text-blue-100/75">{label}<Input required={key !== "accessCode"} value={assessmentForm[key]} type={key === "durationMinutes" ? "number" : "text"} onChange={event => setAssessmentForm(current => ({ ...current, [key]: event.target.value }))} className="mt-1.5 border-white/20 bg-slate-950/40 text-white" /></label>)}<label className="text-xs font-semibold text-blue-100/75">Correct option<select value={assessmentForm.correctOption} onChange={event => setAssessmentForm(current => ({ ...current, correctOption: event.target.value }))} className="mt-1.5 h-9 w-full border border-white/20 bg-slate-950/40 px-3 text-sm text-white"><option value="a">A</option><option value="b">B</option><option value="c">C</option><option value="d">D</option></select></label><Button disabled={createAssessment.isPending} className="w-fit bg-cyan-300 text-[#05205c] hover:bg-cyan-200">{createAssessment.isPending && <Loader2 className="mr-2 size-4 animate-spin" />}Save validated draft</Button></form></div></section>
    <section className="blueprint-panel mt-5 p-5"><p className="eyebrow">ASSESSMENT REGISTER</p><h2 className="mt-1 text-xl font-semibold text-white">My authored assessments</h2>{visibleTests.length ? <div className="mt-5 overflow-auto"><table className="technical-table"><thead><tr><th>Assessment</th><th>Window</th><th>Code policy</th><th>Status</th><th>Operations</th></tr></thead><tbody>{visibleTests.map(test => <tr key={test.id}><td className="font-semibold text-white">{test.title}</td><td>{new Date(test.startAt).toLocaleString()}</td><td>{test.accessCodeEnabled ? test.accessCode : "Disabled"}</td><td><span className="technical-chip">{test.status}</span></td><td><div className="flex flex-wrap gap-2">{test.status === "DRAFT" && <button onClick={() => publish.mutate({ assessmentId: test.id })} className="technical-chip hover:border-cyan-200">Publish</button>}<button disabled={!activeStudentIds.length} onClick={() => assign.mutate({ assessmentId: test.id, studentIds: activeStudentIds })} className="technical-chip hover:border-cyan-200"><Send className="mr-1 size-3" />Assign active ({activeStudentIds.length})</button></div></td></tr>)}</tbody></table></div> : <p className="empty-state">No authored assessments match the current filter.</p>}</section>
    <section className="blueprint-panel mt-5 p-5"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">RESULTS / INTEGRITY REVIEW</p><h2 className="mt-1 text-xl font-semibold text-white">Teacher-scoped assessment results</h2></div><button onClick={exportResults} className="inline-flex items-center gap-2 text-xs font-bold text-cyan-200 hover:text-white"><Download className="size-4" />Export results</button></div>{visibleResults.length ? <div className="mt-5 overflow-auto"><table className="technical-table"><thead><tr><th>Assessment</th><th>Student</th><th>Score</th><th>Integrity</th><th>Status</th></tr></thead><tbody>{visibleResults.map(result => <tr key={result.attemptId}><td className="font-semibold text-white">{result.assessmentTitle}</td><td>{result.studentName}</td><td>{result.score} ({result.percentage}%)</td><td>{result.violationCount} events</td><td><span className="technical-chip">{result.status}</span></td></tr>)}</tbody></table></div> : <p className="empty-state">No submitted attempts match the current filter.</p>}</section><ActivityLogPanel /><div className="mt-5"><StudentImportPanel /></div></BlueprintShell>;
}
