import { afterAll, describe, expect, it } from "vitest";
import { closeMongo, getMongoDb } from "./mongo";

const integrationDescribe = process.env.RUN_MONGO_INTEGRATION === "true" ? describe : describe.skip;
const suffix = `${Date.now()}_${Math.random().toString(36).slice(2)}`;

integrationDescribe("MongoDB commercial tenant constraints", () => {
  afterAll(async () => { const db = await getMongoDb(); await Promise.all([db.collection(`test_credentials_${suffix}`).drop().catch(() => undefined), db.collection(`test_attempts_${suffix}`).drop().catch(() => undefined)]); await closeMongo(); });
  it("rejects matching issued credentials in one institution and permits them in another", async () => { const users = (await getMongoDb()).collection(`test_credentials_${suffix}`); await users.createIndex({ schoolId: 1, username: 1 }, { unique: true, partialFilterExpression: { schoolId: { $type: "number" }, username: { $type: "string" } } }); await users.createIndex({ schoolId: 1, email: 1 }, { unique: true, partialFilterExpression: { schoolId: { $type: "number" }, email: { $type: "string" } } }); await users.insertOne({ schoolId: 1, username: "sam", email: "sam@example.edu" }); await expect(users.insertOne({ schoolId: 1, username: "sam", email: "other@example.edu" })).rejects.toMatchObject({ code: 11000 }); await expect(users.insertOne({ schoolId: 1, username: "other", email: "sam@example.edu" })).rejects.toMatchObject({ code: 11000 }); await expect(users.insertOne({ schoolId: 2, username: "sam", email: "sam@example.edu" })).resolves.toMatchObject({ acknowledged: true }); }, 30_000);
  it("blocks a second active attempt and permits a new active attempt after submission", async () => { const attempts = (await getMongoDb()).collection(`test_attempts_${suffix}`); await attempts.createIndex({ assessmentId: 1, studentId: 1, status: 1 }, { unique: true, partialFilterExpression: { status: "IN_PROGRESS" } }); await attempts.insertOne({ assessmentId: 19, studentId: 8, status: "IN_PROGRESS" }); await expect(attempts.insertOne({ assessmentId: 19, studentId: 8, status: "IN_PROGRESS" })).rejects.toMatchObject({ code: 11000 }); await attempts.updateOne({ assessmentId: 19, studentId: 8, status: "IN_PROGRESS" }, { $set: { status: "SUBMITTED" } }); await expect(attempts.insertOne({ assessmentId: 19, studentId: 8, status: "IN_PROGRESS" })).resolves.toMatchObject({ acknowledged: true }); }, 30_000);
});
